spring:
  #云配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BornToRain/atum
          search-paths: config-repo
      label: dev
      profile: ${spring.profiles}

server:
  #端口
  port: 8888

---

spring:
  profiles: default

#服务注册
eureka:
  instance:
   hostname: localhost
  client:
    #注册地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

---

spring:
  profiles: dev

#服务注册
eureka:
  instance:
   hostname: wxtest.oasisapp.cn
  client:
    #注册地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
