spring:
  profiles: prod
  #云配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BornToRain/atum
          search-paths: config-repo
      label: master
      profile: prod

server:
  #端口
  port: 8888

#服务注册
eureka:
  instance:
   hostname: wechat.oasiscare.cn
  client:
    #注册地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
