spring:
  #云配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BornToRain/atum
          search-paths: config-repo
      label: dev

server:
  #端口
  port: 8888

#服务注册
eureka:
  instance:
    prefer-ip-address: true
  client:
    #注册地址
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: dev
  #云配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BornToRain/atum
          search-paths: config-repo
      label: dev
      profile: dev

server:
  #端口
  port: 8888

#服务注册
eureka:
  instance:
    prefer-ip-address: true
  client:
    #注册地址
    service-url:
      defaultZone: http://localhost:8761/eureka/