#application 统一配置
#Spring配置
spring:
  #队列配置
  rabbitmq:
    host: 60.205.106.190
    port: 5672

logging:
  #日志存放位置
  file: logs/${spring.application.name}.log

#服务注册
eureka:
  instance:
    hostname: localhost
  client:
    #注册地址
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8761/eureka/

#方便其他配置文件调用
accounts:
  port: 1111

#超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#权限设置
security:
  basic:
    enabled: false
  user:
    name: "{cipher}AQAY0laliUc6whqoJBQJXa/LXTB7W8w5TE2uq9bj5KqBUhLKYkduzvyQzQkf8MweiZy87FlTLjO8l4KDMjxYhnwluYxyenA4vqvrUYYmTdWEjhiblZ79zpVWsk4oa+tKEaPdIH9r7kQsF8s2nPtfsoicJsPcSZFVMH85JlYW+4iglorP9p3RthkwE44gA8RNSgu/7qQDlc0ErMhWA93cbYINTgLHJnOQT7dxOAkIPsmbtQtFUKFN1O7Ha9gqtws8Kc/oiRp2bIBkL9MFdnY6mVKQtRIIQFnqDEbzZ/WxQOhkASGYdR2tpdeRujD+/CnnaW9O474Bjazv/AkaTqnD+rk1H2jcRR7rGB7tEwSLDN0aiJeReo9arS+nEHJhkI7TVaI="
    password: "{cipher}AQAY0laliUc6whqoJBQJXa/LXTB7W8w5TE2uq9bj5KqBUhLKYkduzvyQzQkf8MweiZy87FlTLjO8l4KDMjxYhnwluYxyenA4vqvrUYYmTdWEjhiblZ79zpVWsk4oa+tKEaPdIH9r7kQsF8s2nPtfsoicJsPcSZFVMH85JlYW+4iglorP9p3RthkwE44gA8RNSgu/7qQDlc0ErMhWA93cbYINTgLHJnOQT7dxOAkIPsmbtQtFUKFN1O7Ha9gqtws8Kc/oiRp2bIBkL9MFdnY6mVKQtRIIQFnqDEbzZ/WxQOhkASGYdR2tpdeRujD+/CnnaW9O474Bjazv/AkaTqnD+rk1H2jcRR7rGB7tEwSLDN0aiJeReo9arS+nEHJhkI7TVaI="
  #无状态
  sessions: stateless
  headers:
    #禁用Header缓存
    cache: false
  #禁用CsrfToken
  enable-csrf: false
  #oauth2授权
  oauth2:
    #资源设置
    resource:
      #获取用户信息Uri
      user-info-uri: http://${eureka.instance.hostname}:${accounts.port}/v2/me
      #不使用check_token
      prefer-token-info: false
      #令牌类型 Json Web Token
      token-type: Bearer

---

#application 统一配置
#Spring配置
spring:
  profiles: dev
  #队列配置
  rabbitmq:
    host: 60.205.106.190
    port: 5672

logging:
  #日志存放位置
  file: logs/${spring.application.name}.log

#服务注册
eureka:
  instance:
    hostname: wxtest.oasisapp.cn
  client:
    #注册地址
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8761/eureka/

#方便其他配置文件调用
accounts:
  port: 1111

#权限设置
security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin
  #无状态
  sessions: stateless
  headers:
    #禁用Header缓存
    cache: false
  #禁用CsrfToken
  enable-csrf: false
  #oauth2授权
  oauth2:
    #资源设置
    resource:
      #获取用户信息Uri
      user-info-uri: http://wxtest.oasisapp.cn:${accounts.port}/v2/me
      #不使用check_token
      prefer-token-info: false
      #令牌类型 Json Web Token
      token-type: Bearer

---

#application 统一配置
#Spring配置
spring:
  profiles: prod
  #队列配置
  rabbitmq:
    host: 123.56.188.106
    port: 5672

logging:
  #日志存放位置
  file: logs/${spring.application.name}.log

#服务注册
eureka:
  instance:
    hostname: wechat.oasiscare.cn
  client:
    #注册地址
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8761/eureka/

#方便其他配置文件调用
accounts:
  port: 1111

#权限设置
security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin
  #无状态
  sessions: stateless
  headers:
    #禁用Header缓存
    cache: false
  #禁用CsrfToken
  enable-csrf: false
  #oauth2授权
  oauth2:
    #资源设置
    resource:
      #获取用户信息Uri
      user-info-uri: http://wechat.oasiscare.cn:${accounts.port}/v2/me
      #不使用check_token
      prefer-token-info: false
      #令牌类型 Json Web Token
      token-type: Bearer

---

#application 统一配置
#Spring配置
spring:
  profiles: docker
  #队列配置
  rabbitmq:
    host: 123.56.188.106
    port: 5672

logging:
  #日志存放位置
  file: logs/${spring.application.name}.log

#服务注册
eureka:
  client:
    #注册地址
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST}

#方便其他配置文件调用
accounts:
  port: 1111

#权限设置
security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin
  #无状态
  sessions: stateless
  headers:
    #禁用Header缓存
    cache: false
  #禁用CsrfToken
  enable-csrf: false
  #oauth2授权
  oauth2:
    #资源设置
    resource:
      #获取用户信息Uri
      user-info-uri: http://wechat.oasiscare.cn:${accounts.port}/v2/me
      #不使用check_token
      prefer-token-info: false
      #令牌类型 Json Web Token
      token-type: Bearer