#application 统一配置
#Spring配置
spring:
  profiles: prod
  #队列配置
  rabbitmq:
    host: 123.56.188.106
    port: 5672

logging:
  #日志存放位置
  file: logs/${spring.application.name}.log

#服务注册
eureka:
  instance:
    hostname: wechat.oasiscare.cn
  client:
    #注册地址
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8761/eureka/

#方便其他配置文件调用
accounts:
  port: 1111

#权限设置
security:
  basic:
    enabled: false
  #基础认证账号密码
  user:
    name: "{cipher}AQBZdhOg17JcQYqSpv2spWXXZwWzscY3IIFrJcv+49YOx6AJ4ASdQQrbY7/5Fj514/k5D8po05XHV0mtSJkOgQaLlH80LKt8Jg8rRK/X/N1xx81jjC5o3URFNur4lhoTnFlER6KCJ1D9d6ISoy00JhtmAhwbRirBZwjJSsJmDAZ12r4eyL56keNHFLT87JsY8XMWVaUFLD+Uw7rkecodya0ZqKt1I6E2+sVkNlzb6qKN313V2qWX7J/I1duVTXwdaCtYYkM8OwHLydDqVHS3usCfQo34PpTy1ULeXJl8Msqldlo+kFxVlBsfUK7+8Um2fGCdbyYzkU5kTesCauuibx+WksLm6Kkk8jMHn77m2oVZ5L3thdy2rLb1dArnkrYzkzY="
    password: "{cipher}AQBZdhOg17JcQYqSpv2spWXXZwWzscY3IIFrJcv+49YOx6AJ4ASdQQrbY7/5Fj514/k5D8po05XHV0mtSJkOgQaLlH80LKt8Jg8rRK/X/N1xx81jjC5o3URFNur4lhoTnFlER6KCJ1D9d6ISoy00JhtmAhwbRirBZwjJSsJmDAZ12r4eyL56keNHFLT87JsY8XMWVaUFLD+Uw7rkecodya0ZqKt1I6E2+sVkNlzb6qKN313V2qWX7J/I1duVTXwdaCtYYkM8OwHLydDqVHS3usCfQo34PpTy1ULeXJl8Msqldlo+kFxVlBsfUK7+8Um2fGCdbyYzkU5kTesCauuibx+WksLm6Kkk8jMHn77m2oVZ5L3thdy2rLb1dArnkrYzkzY="
  #无状态
  sessions: stateless
  headers:
    #禁用Header缓存
    cache: false
  #禁用CsrfToken
  enable-csrf: false
  #oauth2授权
  oauth2:
    #资源设置
    resource:
      #获取用户信息Uri
      user-info-uri: http://wechat.oasiscare.cn:${accounts.port}/v2/me
      #不使用check_token
      prefer-token-info: false
      #令牌类型 Json Web Token
      token-type: Bearer

---

#application 统一配置
#Spring配置
spring:
  profiles: docker
  #队列配置
  rabbitmq:
    host: 123.56.188.106
    port: 5672

logging:
  #日志存放位置
  file: logs/${spring.application.name}.log

#服务注册
eureka:
  client:
    #注册地址
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST}

#方便其他配置文件调用
accounts:
  port: 1111

#权限设置
security:
  basic:
    enabled: false
  #基础认证账号密码
  user:
    name: "{cipher}AQBZdhOg17JcQYqSpv2spWXXZwWzscY3IIFrJcv+49YOx6AJ4ASdQQrbY7/5Fj514/k5D8po05XHV0mtSJkOgQaLlH80LKt8Jg8rRK/X/N1xx81jjC5o3URFNur4lhoTnFlER6KCJ1D9d6ISoy00JhtmAhwbRirBZwjJSsJmDAZ12r4eyL56keNHFLT87JsY8XMWVaUFLD+Uw7rkecodya0ZqKt1I6E2+sVkNlzb6qKN313V2qWX7J/I1duVTXwdaCtYYkM8OwHLydDqVHS3usCfQo34PpTy1ULeXJl8Msqldlo+kFxVlBsfUK7+8Um2fGCdbyYzkU5kTesCauuibx+WksLm6Kkk8jMHn77m2oVZ5L3thdy2rLb1dArnkrYzkzY="
    password: "{cipher}AQBZdhOg17JcQYqSpv2spWXXZwWzscY3IIFrJcv+49YOx6AJ4ASdQQrbY7/5Fj514/k5D8po05XHV0mtSJkOgQaLlH80LKt8Jg8rRK/X/N1xx81jjC5o3URFNur4lhoTnFlER6KCJ1D9d6ISoy00JhtmAhwbRirBZwjJSsJmDAZ12r4eyL56keNHFLT87JsY8XMWVaUFLD+Uw7rkecodya0ZqKt1I6E2+sVkNlzb6qKN313V2qWX7J/I1duVTXwdaCtYYkM8OwHLydDqVHS3usCfQo34PpTy1ULeXJl8Msqldlo+kFxVlBsfUK7+8Um2fGCdbyYzkU5kTesCauuibx+WksLm6Kkk8jMHn77m2oVZ5L3thdy2rLb1dArnkrYzkzY="
  #无状态
  sessions: stateless
  headers:
    #禁用Header缓存
    cache: false
  #禁用CsrfToken
  enable-csrf: false
  #oauth2授权
  oauth2:
    #资源设置
    resource:
      #获取用户信息Uri
      user-info-uri: http://wechat.oasiscare.cn:${accounts.port}/v2/me
      #不使用check_token
      prefer-token-info: false
      #令牌类型 Json Web Token
      token-type: Bearer