spring:
  profiles: prod
  data:
    #mongodb设置
    mongodb:
      host: wechat.oasiscare.cn
      port: 9999
      database: commons
      events:
        collection.name: events
        snapshot.collection.name: snapshots
      username: oasis
      password: oasisadmin
  #Redis配置
  redis:
    port: 6379
    #主机地址
    host: 10.25.95.108
    pool:
      #连接池最大的活跃连接数，-1表示无限
      max-active: 8
      #连接池最大的空闲连接数，-1表示无限
      max-idle: 8
      #当连接池耗尽时，新获取连接需要等待的最大时间，以毫秒单位，-1表示无限等待
      max-wait: 30
      #连接池中空闲连接的最小数量
      min-idle: 3
    #连接超时时间，毫秒单位
    timeout: 2000
    password: oasisadmin

server:
  #端口
  port: 2222
  #开启压缩
  compression:
    enabled: true
    #需要压缩的类型
    mime-types: text/xml,text/plain,text/css,text/javascript,application/xml,application/json,application/javascript
    #最小压缩响应字节数
    min-response-size: 1024

#权限设置
security:
  basic:
    enable: false
  #基础认证账号密码
  user:
    name: "{cipher}AQBZdhOg17JcQYqSpv2spWXXZwWzscY3IIFrJcv+49YOx6AJ4ASdQQrbY7/5Fj514/k5D8po05XHV0mtSJkOgQaLlH80LKt8Jg8rRK/X/N1xx81jjC5o3URFNur4lhoTnFlER6KCJ1D9d6ISoy00JhtmAhwbRirBZwjJSsJmDAZ12r4eyL56keNHFLT87JsY8XMWVaUFLD+Uw7rkecodya0ZqKt1I6E2+sVkNlzb6qKN313V2qWX7J/I1duVTXwdaCtYYkM8OwHLydDqVHS3usCfQo34PpTy1ULeXJl8Msqldlo+kFxVlBsfUK7+8Um2fGCdbyYzkU5kTesCauuibx+WksLm6Kkk8jMHn77m2oVZ5L3thdy2rLb1dArnkrYzkzY="
    password: "{cipher}AQBZdhOg17JcQYqSpv2spWXXZwWzscY3IIFrJcv+49YOx6AJ4ASdQQrbY7/5Fj514/k5D8po05XHV0mtSJkOgQaLlH80LKt8Jg8rRK/X/N1xx81jjC5o3URFNur4lhoTnFlER6KCJ1D9d6ISoy00JhtmAhwbRirBZwjJSsJmDAZ12r4eyL56keNHFLT87JsY8XMWVaUFLD+Uw7rkecodya0ZqKt1I6E2+sVkNlzb6qKN313V2qWX7J/I1duVTXwdaCtYYkM8OwHLydDqVHS3usCfQo34PpTy1ULeXJl8Msqldlo+kFxVlBsfUK7+8Um2fGCdbyYzkU5kTesCauuibx+WksLm6Kkk8jMHn77m2oVZ5L3thdy2rLb1dArnkrYzkzY="
  #oauth2授权
  oauth2:
    #客户端设置
    client:
      clientId: commons
      clientSecret: commons
      #token获取Uri
      accessTokenUri: http://wechat.oasiscare.cn:${accounts.port}/oauth/token
      #授权类型 客户端
      grant-type: client_credentials
      #授权范围
      scope: server

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

axon:
  #DistributedCommandBus
  #分布式的CommandBus实现,由多个CommandBus的实例组成,并一起工作来分担负载.
  distributed:
    enabled: true
  amqp:
    exchange: amq.fanout
  eventhandling:
    processors:
      commons:
        source: queueMessageSource

#阿里云短信
sms:
  #阿里云密钥
  access-secret: "{cipher}AQAEOQq1sw3KWxNzK9cSmSdi17Xxpn/xegH85izd6Kq58rWUIfS/7hd5tXK0uwTpdd2bDuySMwdWSc+PlesNQEg5y0pxpsqhy/334X3Y80oBDnd9FxV6IqIQqvpUSygFHlcLsq7k6keyACIGC+8cpjsrTQnjLD7tMBtfh/JW0Fnv4+r/xF/avehYU65mZHYX5cEe41/FCQZ3ylXu7fAmDAwu3UtchQ7t1sjhcryNM2c7hsBTVWVIMu6XBALgEHIFgYWNSKaT3Soa8PAyFq/sU+i3ytlrIXA5686WyGfQVCTJU5JKhBkSeFKYe+WCFDkl2E7ULqUGIa2Q3fQJCeKR8BK/fAKOT2QUd+H2aswxehJ5vOSmGZF+aFeoNX7LWj/COIwwVMRDzyceKj5o9K9wT0YI"
