spring:
  data:
    #mongodb设置
    mongodb:
      host: wxtest.oasisapp.cn
      port: 9999
      database: commons
      events:
        collection.name: events
        snapshot.collection.name: snapshots
      username: "{cipher}AQBTDa/nbmd0cVNt66iKV+idQZlppXu/zoziTQ+fqg6s7+ksufryFg6bryo1R+r92vGdplc+HWVM760MY9ABhXleTE3eeQOU+DbgC3JETtcbxT0CQbM66a//v/fIqFbZxo680cm8A8kbmCGhHo+6VQ/9hpq8J4E9XBItlR1S3ipm9wkMdY+kldhK4oUDVSzf1VnbDpCkJ7fvVwWWLYQaNjIQJhdAFKg4/t1Y4KmyNj98ecCGkN1NY8iRnbNbr476nMLn+h95JKz5tcSynmewpWdVg7GQIw/cPldZw6fgv51FSg2ii87wuGfl2HHlmoG+o4K0pt5RWi1SDMxZ/aSK7M/CdAvE2+yx6nypwPnUS2qIZTUkk8mBw4lWPi7VYrDc6AU="
      password: "{cipher}AQBQdIalnRqhEllF+JP6FsARIBHFzxa7iHpZdLZUC9r0M2T5epyMmUTsDos3TFjKJPne/52kTcvajeAZz9zU9AlX6JklrFRmSV/vbHC+W69XGqMbzjsGrVwdLLrbj1DlVZ8ghSBtGv9C8XHiuF7EYC5Fee78NwfR27e5fP4QKwU6UQJU8YXMLpZ1isqv5bsCKDBIXMxUMb2NFZnmLtJHxdQihsSAe21P17OcscFU9GHBEctGjIqvDxSYSTx2iFJG/gA8WyenKF1B5yo1pGQN34GMeSKvZhCytzxlhDW0AvrYEK2OBtUf3EXrLl/UcaXZk0AXb4OIOAI1Q/G7qjc+U/b6fD0GNw0fjMxZsTEYrDK4akRFZbpJHEAC2L/C0qWt4tQ="
  #Redis配置
  redis:
    port: 6379
    #主机地址
    host: wxtest.oasisapp.cn
    pool:
      #连接池最大的活跃连接数，-1表示无限
      max-active: 8
      #连接池最大的空闲连接数，-1表示无限
      max-idle: 8
      #当连接池耗尽时，新获取连接需要等待的最大时间，以毫秒单位，-1表示无限等待
      max-wait: 30
      #连接池中空闲连接的最小数量
      min-idle: 3
    #连接超时时间，毫秒单位
    timeout: 2000
    password: "{cipher}AQBQdIalnRqhEllF+JP6FsARIBHFzxa7iHpZdLZUC9r0M2T5epyMmUTsDos3TFjKJPne/52kTcvajeAZz9zU9AlX6JklrFRmSV/vbHC+W69XGqMbzjsGrVwdLLrbj1DlVZ8ghSBtGv9C8XHiuF7EYC5Fee78NwfR27e5fP4QKwU6UQJU8YXMLpZ1isqv5bsCKDBIXMxUMb2NFZnmLtJHxdQihsSAe21P17OcscFU9GHBEctGjIqvDxSYSTx2iFJG/gA8WyenKF1B5yo1pGQN34GMeSKvZhCytzxlhDW0AvrYEK2OBtUf3EXrLl/UcaXZk0AXb4OIOAI1Q/G7qjc+U/b6fD0GNw0fjMxZsTEYrDK4akRFZbpJHEAC2L/C0qWt4tQ="


server:
  #端口
  port: 3333
  tomcat:
    #容器编码
    uri-encoding: utf-8
  #开启压缩
  compression:
    enabled: true
    #需要压缩的类型
    mime-types: text/xml,text/plain,text/css,text/javascript,application/xml,application/json,application/javascript
    #最小压缩响应字节数
    min-response-size: 1024

#权限设置
security:
  basic:
    enable: false
  #基础认证账号密码
  user:
    name: "{cipher}AQBZdhOg17JcQYqSpv2spWXXZwWzscY3IIFrJcv+49YOx6AJ4ASdQQrbY7/5Fj514/k5D8po05XHV0mtSJkOgQaLlH80LKt8Jg8rRK/X/N1xx81jjC5o3URFNur4lhoTnFlER6KCJ1D9d6ISoy00JhtmAhwbRirBZwjJSsJmDAZ12r4eyL56keNHFLT87JsY8XMWVaUFLD+Uw7rkecodya0ZqKt1I6E2+sVkNlzb6qKN313V2qWX7J/I1duVTXwdaCtYYkM8OwHLydDqVHS3usCfQo34PpTy1ULeXJl8Msqldlo+kFxVlBsfUK7+8Um2fGCdbyYzkU5kTesCauuibx+WksLm6Kkk8jMHn77m2oVZ5L3thdy2rLb1dArnkrYzkzY="
    password: "{cipher}AQBZdhOg17JcQYqSpv2spWXXZwWzscY3IIFrJcv+49YOx6AJ4ASdQQrbY7/5Fj514/k5D8po05XHV0mtSJkOgQaLlH80LKt8Jg8rRK/X/N1xx81jjC5o3URFNur4lhoTnFlER6KCJ1D9d6ISoy00JhtmAhwbRirBZwjJSsJmDAZ12r4eyL56keNHFLT87JsY8XMWVaUFLD+Uw7rkecodya0ZqKt1I6E2+sVkNlzb6qKN313V2qWX7J/I1duVTXwdaCtYYkM8OwHLydDqVHS3usCfQo34PpTy1ULeXJl8Msqldlo+kFxVlBsfUK7+8Um2fGCdbyYzkU5kTesCauuibx+WksLm6Kkk8jMHn77m2oVZ5L3thdy2rLb1dArnkrYzkzY="
  #oauth2授权
  oauth2:
    #客户端设置
    client:
      clientId: wechat
      clientSecret: wechat
      #token获取Uri
      accessTokenUri: http://localhost:${accounts.port}/oauth/token
      #授权类型 客户端
      grant-type: client_credentials
      #授权范围
      scope: server

feign:
  #开启压缩
  compression:
    enabled: true
    #需要压缩的类型
    mime-types: text/xml,text/plain,text/css,text/javascript,application/xml,application/json,application/javascript
    #最小压缩响应字节数
    min-response-size: 1024
    response.enable: true
  hystrix.enabled: true
  httpclient.enabled: true

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

axon:
  #DistributedCommandBus
  #分布式的CommandBus实现,由多个CommandBus的实例组成,并一起工作来分担负载.
  distributed:
    enabled: true
  amqp:
    exchange: amq.fanout
  eventhandling:
    processors:
      wechat:
        source: queueMessageSource

#微信设置
wechat:
  #是否启用Js-SDK
  enable-js-api: true
  #是否启用微信卡券
  enable-api-ticket: true
  #应用密钥
  secret: "{cipher}AQCYlEfcjuMv4RwacJZDkOD2qMy+2duLM9eqb04+n5a3aupy89M+1RoVCLxyNPP2SFnKs8cfW5wsw2Rh4lJofsUKNKlGj1kevrdwUy7RQOFYbI1I7hBaENoSmgztLrU37VnCD5K21RuOChUR4mxaKJPx4amDIxwo/IkmI0mstZAYM3WrdgngMFJrS6aLW5TaYWbI+85zO56geAFcA5tOzMaSiisM7q30zk2R0AtMIeOXghndKRewQXowijV1glJmprHhcaU7Uz2C6s5AGNq/10+BaAaMPDbSE1TDoKHMma2sP3WrUKupwbthSIidbv87n9TO43p+ZiJA8ioVKU0l5t8am3wL/0KgmXO7BN4m33D6l3ZGr6AlajA8KmTJ93fbShSPk8MZnHv5Y5pGJhc2JtKIJZnULyPgo8q3FicDFwb90Q=="

---

#开发环境
spring:
  profiles: dev
  data:
   #mongodb设置
   mongodb:
     host: wxtest.oasisapp.cn
     port: 9999
     database: commons
     events:
       collection.name: events
       snapshot.collection.name: snapshots
     username: "{cipher}AQBTDa/nbmd0cVNt66iKV+idQZlppXu/zoziTQ+fqg6s7+ksufryFg6bryo1R+r92vGdplc+HWVM760MY9ABhXleTE3eeQOU+DbgC3JETtcbxT0CQbM66a//v/fIqFbZxo680cm8A8kbmCGhHo+6VQ/9hpq8J4E9XBItlR1S3ipm9wkMdY+kldhK4oUDVSzf1VnbDpCkJ7fvVwWWLYQaNjIQJhdAFKg4/t1Y4KmyNj98ecCGkN1NY8iRnbNbr476nMLn+h95JKz5tcSynmewpWdVg7GQIw/cPldZw6fgv51FSg2ii87wuGfl2HHlmoG+o4K0pt5RWi1SDMxZ/aSK7M/CdAvE2+yx6nypwPnUS2qIZTUkk8mBw4lWPi7VYrDc6AU="
     password: "{cipher}AQBQdIalnRqhEllF+JP6FsARIBHFzxa7iHpZdLZUC9r0M2T5epyMmUTsDos3TFjKJPne/52kTcvajeAZz9zU9AlX6JklrFRmSV/vbHC+W69XGqMbzjsGrVwdLLrbj1DlVZ8ghSBtGv9C8XHiuF7EYC5Fee78NwfR27e5fP4QKwU6UQJU8YXMLpZ1isqv5bsCKDBIXMxUMb2NFZnmLtJHxdQihsSAe21P17OcscFU9GHBEctGjIqvDxSYSTx2iFJG/gA8WyenKF1B5yo1pGQN34GMeSKvZhCytzxlhDW0AvrYEK2OBtUf3EXrLl/UcaXZk0AXb4OIOAI1Q/G7qjc+U/b6fD0GNw0fjMxZsTEYrDK4akRFZbpJHEAC2L/C0qWt4tQ="
 #Redis配置
 redis:
   port: 6379
   #主机地址
   host: wxtest.oasisapp.cn
   pool:
     #连接池最大的活跃连接数，-1表示无限
     max-active: 8
     #连接池最大的空闲连接数，-1表示无限
     max-idle: 8
     #当连接池耗尽时，新获取连接需要等待的最大时间，以毫秒单位，-1表示无限等待
     max-wait: 30
     #连接池中空闲连接的最小数量
     min-idle: 3
   #连接超时时间，毫秒单位
   timeout: 2000
   password: "{cipher}AQBQdIalnRqhEllF+JP6FsARIBHFzxa7iHpZdLZUC9r0M2T5epyMmUTsDos3TFjKJPne/52kTcvajeAZz9zU9AlX6JklrFRmSV/vbHC+W69XGqMbzjsGrVwdLLrbj1DlVZ8ghSBtGv9C8XHiuF7EYC5Fee78NwfR27e5fP4QKwU6UQJU8YXMLpZ1isqv5bsCKDBIXMxUMb2NFZnmLtJHxdQihsSAe21P17OcscFU9GHBEctGjIqvDxSYSTx2iFJG/gA8WyenKF1B5yo1pGQN34GMeSKvZhCytzxlhDW0AvrYEK2OBtUf3EXrLl/UcaXZk0AXb4OIOAI1Q/G7qjc+U/b6fD0GNw0fjMxZsTEYrDK4akRFZbpJHEAC2L/C0qWt4tQ="


server:
  #端口
  port: 3333
  tomcat:
    #容器编码
    uri-encoding: utf-8
  #开启压缩
  compression:
    enabled: true
    #需要压缩的类型
    mime-types: text/xml,text/plain,text/css,text/javascript,application/xml,application/json,application/javascript
    #最小压缩响应字节数
    min-response-size: 1024

#权限设置
security:
  basic:
    enable: false
  #基础认证账号密码
  user:
    name: "{cipher}AQBZdhOg17JcQYqSpv2spWXXZwWzscY3IIFrJcv+49YOx6AJ4ASdQQrbY7/5Fj514/k5D8po05XHV0mtSJkOgQaLlH80LKt8Jg8rRK/X/N1xx81jjC5o3URFNur4lhoTnFlER6KCJ1D9d6ISoy00JhtmAhwbRirBZwjJSsJmDAZ12r4eyL56keNHFLT87JsY8XMWVaUFLD+Uw7rkecodya0ZqKt1I6E2+sVkNlzb6qKN313V2qWX7J/I1duVTXwdaCtYYkM8OwHLydDqVHS3usCfQo34PpTy1ULeXJl8Msqldlo+kFxVlBsfUK7+8Um2fGCdbyYzkU5kTesCauuibx+WksLm6Kkk8jMHn77m2oVZ5L3thdy2rLb1dArnkrYzkzY="
    password: "{cipher}AQBZdhOg17JcQYqSpv2spWXXZwWzscY3IIFrJcv+49YOx6AJ4ASdQQrbY7/5Fj514/k5D8po05XHV0mtSJkOgQaLlH80LKt8Jg8rRK/X/N1xx81jjC5o3URFNur4lhoTnFlER6KCJ1D9d6ISoy00JhtmAhwbRirBZwjJSsJmDAZ12r4eyL56keNHFLT87JsY8XMWVaUFLD+Uw7rkecodya0ZqKt1I6E2+sVkNlzb6qKN313V2qWX7J/I1duVTXwdaCtYYkM8OwHLydDqVHS3usCfQo34PpTy1ULeXJl8Msqldlo+kFxVlBsfUK7+8Um2fGCdbyYzkU5kTesCauuibx+WksLm6Kkk8jMHn77m2oVZ5L3thdy2rLb1dArnkrYzkzY="
  #oauth2授权
  oauth2:
    #客户端设置
    client:
      clientId: wechat
      clientSecret: wechat
      #token获取Uri
      accessTokenUri: http://wxtest.oasisapp.cn:${accounts.port}/oauth/token
      #授权类型 客户端
      grant-type: client_credentials
      #授权范围
      scope: server

feign:
  #开启压缩
  compression:
    enabled: true
    #需要压缩的类型
    mime-types: text/xml,text/plain,text/css,text/javascript,application/xml,application/json,application/javascript
    #最小压缩响应字节数
    min-response-size: 1024
    response.enable: true
  hystrix.enabled: true
  httpclient.enabled: true

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

axon:
  #DistributedCommandBus
  #分布式的CommandBus实现,由多个CommandBus的实例组成,并一起工作来分担负载.
  distributed:
    enabled: true
  amqp:
    exchange: amq.fanout
  eventhandling:
    processors:
      wechat:
        source: queueMessageSource

#微信设置
wechat:
  #是否启用Js-SDK
  enable-js-api: true
  #是否启用微信卡券
  enable-api-ticket: true
  wx-id: 112
  #应用密钥
  secret: "{cipher}AQCYlEfcjuMv4RwacJZDkOD2qMy+2duLM9eqb04+n5a3aupy89M+1RoVCLxyNPP2SFnKs8cfW5wsw2Rh4lJofsUKNKlGj1kevrdwUy7RQOFYbI1I7hBaENoSmgztLrU37VnCD5K21RuOChUR4mxaKJPx4amDIxwo/IkmI0mstZAYM3WrdgngMFJrS6aLW5TaYWbI+85zO56geAFcA5tOzMaSiisM7q30zk2R0AtMIeOXghndKRewQXowijV1glJmprHhcaU7Uz2C6s5AGNq/10+BaAaMPDbSE1TDoKHMma2sP3WrUKupwbthSIidbv87n9TO43p+ZiJA8ioVKU0l5t8am3wL/0KgmXO7BN4m33D6l3ZGr6AlajA8KmTJ93fbShSPk8MZnHv5Y5pGJhc2JtKIJZnULyPgo8q3FicDFwb90Q=="

---

#正式环境
spring:
  profiles: prod
  data:
    #mongodb设置
    mongodb:
      host: wechat.oasiscare.cn
      port: 9999
      database: commons
      events:
        collection.name: events
        snapshot.collection.name: snapshots
      username: "{cipher}AQBTDa/nbmd0cVNt66iKV+idQZlppXu/zoziTQ+fqg6s7+ksufryFg6bryo1R+r92vGdplc+HWVM760MY9ABhXleTE3eeQOU+DbgC3JETtcbxT0CQbM66a//v/fIqFbZxo680cm8A8kbmCGhHo+6VQ/9hpq8J4E9XBItlR1S3ipm9wkMdY+kldhK4oUDVSzf1VnbDpCkJ7fvVwWWLYQaNjIQJhdAFKg4/t1Y4KmyNj98ecCGkN1NY8iRnbNbr476nMLn+h95JKz5tcSynmewpWdVg7GQIw/cPldZw6fgv51FSg2ii87wuGfl2HHlmoG+o4K0pt5RWi1SDMxZ/aSK7M/CdAvE2+yx6nypwPnUS2qIZTUkk8mBw4lWPi7VYrDc6AU="
      password: "{cipher}AQBQdIalnRqhEllF+JP6FsARIBHFzxa7iHpZdLZUC9r0M2T5epyMmUTsDos3TFjKJPne/52kTcvajeAZz9zU9AlX6JklrFRmSV/vbHC+W69XGqMbzjsGrVwdLLrbj1DlVZ8ghSBtGv9C8XHiuF7EYC5Fee78NwfR27e5fP4QKwU6UQJU8YXMLpZ1isqv5bsCKDBIXMxUMb2NFZnmLtJHxdQihsSAe21P17OcscFU9GHBEctGjIqvDxSYSTx2iFJG/gA8WyenKF1B5yo1pGQN34GMeSKvZhCytzxlhDW0AvrYEK2OBtUf3EXrLl/UcaXZk0AXb4OIOAI1Q/G7qjc+U/b6fD0GNw0fjMxZsTEYrDK4akRFZbpJHEAC2L/C0qWt4tQ="
  #Redis配置
  redis:
    port: 6379
    #主机地址
    host: 10.25.95.108
    pool:
      #连接池最大的活跃连接数，-1表示无限
      max-active: 8
      #连接池最大的空闲连接数，-1表示无限
      max-idle: 8
      #当连接池耗尽时，新获取连接需要等待的最大时间，以毫秒单位，-1表示无限等待
      max-wait: 30
      #连接池中空闲连接的最小数量
      min-idle: 3
    #连接超时时间，毫秒单位
    timeout: 2000
    password: "{cipher}AQBQdIalnRqhEllF+JP6FsARIBHFzxa7iHpZdLZUC9r0M2T5epyMmUTsDos3TFjKJPne/52kTcvajeAZz9zU9AlX6JklrFRmSV/vbHC+W69XGqMbzjsGrVwdLLrbj1DlVZ8ghSBtGv9C8XHiuF7EYC5Fee78NwfR27e5fP4QKwU6UQJU8YXMLpZ1isqv5bsCKDBIXMxUMb2NFZnmLtJHxdQihsSAe21P17OcscFU9GHBEctGjIqvDxSYSTx2iFJG/gA8WyenKF1B5yo1pGQN34GMeSKvZhCytzxlhDW0AvrYEK2OBtUf3EXrLl/UcaXZk0AXb4OIOAI1Q/G7qjc+U/b6fD0GNw0fjMxZsTEYrDK4akRFZbpJHEAC2L/C0qWt4tQ="

server:
  #端口
  port: 3333
  tomcat:
    #容器编码
    uri-encoding: utf-8
  #开启压缩
  compression:
    enabled: true
    #需要压缩的类型
    mime-types: text/xml,text/plain,text/css,text/javascript,application/xml,application/json,application/javascript
    #最小压缩响应字节数
    min-response-size: 1024

#权限设置
security:
  basic:
    enable: false
  #基础认证账号密码
  user:
    name: "{cipher}AQBZdhOg17JcQYqSpv2spWXXZwWzscY3IIFrJcv+49YOx6AJ4ASdQQrbY7/5Fj514/k5D8po05XHV0mtSJkOgQaLlH80LKt8Jg8rRK/X/N1xx81jjC5o3URFNur4lhoTnFlER6KCJ1D9d6ISoy00JhtmAhwbRirBZwjJSsJmDAZ12r4eyL56keNHFLT87JsY8XMWVaUFLD+Uw7rkecodya0ZqKt1I6E2+sVkNlzb6qKN313V2qWX7J/I1duVTXwdaCtYYkM8OwHLydDqVHS3usCfQo34PpTy1ULeXJl8Msqldlo+kFxVlBsfUK7+8Um2fGCdbyYzkU5kTesCauuibx+WksLm6Kkk8jMHn77m2oVZ5L3thdy2rLb1dArnkrYzkzY="
    password: "{cipher}AQBZdhOg17JcQYqSpv2spWXXZwWzscY3IIFrJcv+49YOx6AJ4ASdQQrbY7/5Fj514/k5D8po05XHV0mtSJkOgQaLlH80LKt8Jg8rRK/X/N1xx81jjC5o3URFNur4lhoTnFlER6KCJ1D9d6ISoy00JhtmAhwbRirBZwjJSsJmDAZ12r4eyL56keNHFLT87JsY8XMWVaUFLD+Uw7rkecodya0ZqKt1I6E2+sVkNlzb6qKN313V2qWX7J/I1duVTXwdaCtYYkM8OwHLydDqVHS3usCfQo34PpTy1ULeXJl8Msqldlo+kFxVlBsfUK7+8Um2fGCdbyYzkU5kTesCauuibx+WksLm6Kkk8jMHn77m2oVZ5L3thdy2rLb1dArnkrYzkzY="
  #oauth2授权
  oauth2:
    #客户端设置
    client:
      clientId: wechat
      clientSecret: wechat
      #token获取Uri
      accessTokenUri: http://wechat.oasiscare.cn:${accounts.port}/oauth/token
      #授权类型 客户端
      grant-type: client_credentials
      #授权范围
      scope: server

feign:
  #开启压缩
  compression:
    enabled: true
    #需要压缩的类型
    mime-types: text/xml,text/plain,text/css,text/javascript,application/xml,application/json,application/javascript
    #最小压缩响应字节数
    min-response-size: 1024
    response.enable: true
  hystrix.enabled: true
  httpclient.enabled: true

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

axon:
  #DistributedCommandBus
  #分布式的CommandBus实现,由多个CommandBus的实例组成,并一起工作来分担负载.
  distributed:
    enabled: true
  amqp:
    exchange: amq.fanout
  eventhandling:
    processors:
      wechat:
        source: queueMessageSource

#微信设置
wechat:
  #应用AD
  app-id: wxe758bf1b8f5dfbcf
  #应用密钥
  secret: "{cipher}AQBmtpmg9UlJFZtf2ljZJ7FgzLZfVlAHovogRqqqtsJ/bK+O54xsKlBMaNSGhq694TpBdstq/tqlXwe2eSyOnGg4AxvcQnq6S79fcHkB6D7c+4iJb1oCgYV78A1kx3oqaa9WXKfKKTkpPMG8dpwl9FZIUD3G1y3J3ydsg+h8AsNf4Um0N+E7v9jeJln9mXrR2L0k364sUwu9SOUbyCwjUfeiDoo9nMQw0nB9rvUekzfXFG/dSTZDASD65E6dOTeDdPaCrBwxymZpJKF1BKEWEPUK+MyulAwVNbs1NutTFeRKQN1naioCcBECL66jywGRrMnIrMkBXqQNAld2etAQA30s7AsVQ3d0cXde5054NvoDwJgNWhjCfHkHdGDZt74qI05uPeW+/XcaeV0X3e7RnKbQAiNqjRVRibh187Nwa0krKQ=="
  #商户号
  mchId: 1238751702
  #微信后台设置的Key
  key: theonlythingwehavetofearisfearit
  #微信后台设置的令牌
  token: weixinZoffConn
  #证书路径
  cert-path:
  #证书密码
  cert-password:
  #是否启用Js-SDK
  enable-js-api: true
  #是否启用微信卡券
  enable-api-ticket: true
  #支付回调地址
  payment-notify-uri: https://buz.oasisapp.cn/honghclient/servlet/WeChatTrade
  #关注标签ID
  wx-id: 103
  #模版ID
  template:
    register: l39CoZRkUmOsku6Puwf7boAcBi6ilu1b-bHE0iSI7ig
    success: D8SjqFLk1_U3M29urX57tlv9v4Ru_Iz2IFVOsZLfYp8
